name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  erl24-25-26:
    name: "Ubuntu"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['24.3.4.15', '25.3.2.9', '26.2.2', '27.0.1']
        rebar: ['3.23.0']
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        version-type: strict
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Checks
      run: make check
